[package]
name = "ssb"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-rs = { version = "0.19.2", default-features = false, features = ["png"] }
hyprland = { version = "0.3.13", default-features = false, features = ["tokio", "listener"] }
image = { version = "0.25.0", default-features = false, features = ["png"] }
smithay-client-toolkit = { version = "0.18.1", default-features = false }
wayland-client = "0.31.2"
