[package]
name = "ssb"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-rs = { version = "0.19.2", features = ["png"] }
hyprland = "0.3.13"
image = "0.24.9"
smithay-client-toolkit = { version = "0.18.1", default_features = false }
sysinfo = "0.30.7"
wayland-client = "0.31.2"
