[package]
name = "ssb"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-rs = { version = "0.19.2", default_features = false, features = ["png"] }
fast_image_resize = "3.0.4"
image = "0.24.9"
serde_json = "1.0.114"
smithay-client-toolkit = { version = "0.18.1", default_features = false }
wayland-client = "0.31.2"
