name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    strategy:
      matrix:
        environment: [Wayland]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: cargo-stable

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt-get install pkg-config libcairo2-dev libpulse-dev

      - name: Run tests
        env:
          LLVM_PROFILE_FILE: grcov-%p-%m.profraw
          RUSTFLAGS: -Cinstrument-coverage
        run: |
          cargo test

      - run: |
          rustup component add llvm-tools-preview
          cargo install grcov
          grcov $(find . -name "grcov-*.profraw" -print) \
            --branch \
            --ignore-not-existing \
            --binary-path ./target/debug/ \
            -s . \
            -t lcov \
            --ignore "/*" \
            -o lcov.info

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          override_branch: main
          fail_ci_if_error: true
